services:
  user-management-service:
    container_name: user_management_api
    build:
      context: ./user-management-service
      args:
        - APP_ENV
      network: host
    command: npm run start
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local
    depends_on:
      - pgsqldb

  api-gateway-service:
    container_name: api-gateway-service
    build:
      context: ./service-discovery
      args:
        - APP_ENV
      network: host
    command: node index.js
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  web3-proxy-service:
    container_name: web3_proxy
    build:
      context: ./web3-proxy-service
      args:
        - APP_ENV
      network: host
    command: npm run start
    ports:
      - 3004:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local

  dao-app:
    container_name: dao_service_api
    build:
      context: ./dao-service
      args:
        - APP_ENV
      network: host
    command: npm run start
    ports:
      - 3002:3000
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env.local

  audit-app:
    container_name: audit_service_api
    build:
      context: ./audit-trail-service
      args:
        - APP_ENV
      network: host
    command: npm run start
    ports:
      - 3003:3000
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.local

  pgsqldb:
    container_name: pgsqldb
    image: postgres:16
    env_file:
      - .env.local
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      # - ./postgresql.conf:/etc/postgresql.conf

  pgadmin:
    container_name: pgadmin4-audit-trail
    image: dpage/pgadmin4:8.0
    env_file:
      - .env.local
    ports:
      - '5070:80'
    depends_on:
      - pgsqldb

volumes:
  postgres-data:


